replicaCount: 1

image:
  # CHANGED: Using your real ECR repository instead of hashicorp/http-echo
  repository: 765288911542.dkr.ecr.us-east-1.amazonaws.com/payment-service
  tag: "1.0.0"
  pullPolicy: Always

service:
  type: ClusterIP
  # Standardized: Internal service port remains 80 for easy discovery
  port: 80
  # FIXED: Matches SERVER_PORT=8085 from your Docker Compose
  targetPort: 8085 

serviceName: "PAYMENT"

resources:
  # INCREASED: Spring Boot needs more than 64Mi to start correctly
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"