replicaCount: 1

image:
  repository: 765288911542.dkr.ecr.us-east-1.amazonaws.com/inventory-service
  tag: "1.0.0"
  pullPolicy: Always

service:
  type: ClusterIP
  # Internal discovery port (standardized at 80)
  port: 80 
  # FIXED: Matches SERVER_PORT=8086 from your Docker Compose
  targetPort: 8086 

serviceName: "INVENTORY"

resources:
  # INCREASED: Safe zone for Java Spring Boot startup
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"