replicaCount: 1
image:
  repository: 765288911542.dkr.ecr.us-east-1.amazonaws.com/api-gateway
  tag: "1.0.0"
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 8089 # Matches Docker Compose SERVER_PORT=8089
resources:
  limits: { memory: "256Mi", cpu: "200m" }
  requests: { memory: "128Mi", cpu: "100m" }