apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway
  namespace: argocd # ArgoCD watches from here
spec:
  project: default
  source:
    repoURL: https://github.com/Solano204/tradeflow-gitops.git
    targetRevision: main
    path: services/api-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: production # Deploys your Java app here
  syncPolicy:
    automated:
      prune: true
      selfHeal: true